# configuration for pre-commit git hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^test_hass/configuration.yaml$
      - id: check-toml
      - id: debug-statements
  - repo: https://github.com/lsst-ts/pre-commit-xmllint
    rev: v1.0.0
    hooks:
      - id: format-xmllint
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-toml
        args: ["--autofix", "--no-sort"]
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.16
    hooks:
      - id: validate-pyproject
        additional_dependencies: ["validate-pyproject-schema-store[all]"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1"
    hooks:
      - id: mypy
        additional_dependencies:
          [
            homeassistant-stubs,
            voluptuous-stubs,
            types-python-dateutil,
            types-PyYAML,
            types-requests,
          ]
  - repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.278
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
