name: CI/CQ

on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  codechecks:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python-${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pre Commit Checks
        uses: pre-commit/action@v3.0.0

      - name: Install Dependencies
        run: pip install .[dev]

      - name: Analysis (git diff)
        if: failure()
        run: git diff
